"""Language-agnostic graph contract and analysis infrastructure."""

from .capabilities import (
    CAPABILITY_COMPLETE,
    CAPABILITY_NONE,
    CAPABILITY_PARTIAL,
    FRONTEND_OWNED_CAPABILITIES,
    OVERLAY_OWNED_CAPABILITIES,
    VALID_CAPABILITY_LEVELS,
)
from .schema import CURRENT_CONTRACT_VERSION, LEGACY_CONTRACT_VERSIONS

__all__ = [
    "CAPABILITY_COMPLETE",
    "CAPABILITY_NONE",
    "CAPABILITY_PARTIAL",
    "CURRENT_CONTRACT_VERSION",
    "FRONTEND_OWNED_CAPABILITIES",
    "LEGACY_CONTRACT_VERSIONS",
    "OVERLAY_OWNED_CAPABILITIES",
    "VALID_CAPABILITY_LEVELS",
]

