use clang_sys::*;
use prost::Message;
use sha2::{Digest, Sha256};
use std::env;
use std::ffi::{CStr, CString};
use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::os::raw::{c_char, c_int, c_uint, c_void};
use std::path::{Path, PathBuf};
use std::ptr;
use rustc_hash::{FxHashMap, FxHashSet};

mod graph {
    include!(concat!(env!("OUT_DIR"), "/lachesis.graph.rs"));
}

const SHARD_FORMAT_VERSION: u32 = 2;

#[derive(Clone, Copy, Eq, Hash, PartialEq)]
struct IdKey([u8; 20]);

fn id_key(id: &str) -> IdKey {
    let mut key = [0u8; 20];
    let bytes = id.as_bytes();
    let start = bytes.len().saturating_sub(key.len());
    let suffix = &bytes[start..];
    if suffix.len() == key.len() {
        key.copy_from_slice(suffix);
    } else {
        // Native IDs are generated by stable_id and always have the 20-byte
        // digest suffix. Keep malformed/external IDs deterministic as well.
        let mut digest = Sha256::new();
        digest.update(bytes);
        let digest = digest.finalize();
        key.copy_from_slice(&digest[..20]);
    }
    IdKey(key)
}

fn frame(file: &mut File, payload: &[u8]) -> io::Result<()> {
    let size = u32::try_from(payload.len())
        .map_err(|_| io::Error::new(io::ErrorKind::InvalidData, "record exceeds 4 GiB"))?;
    file.write_all(&size.to_be_bytes())?;
    file.write_all(payload)
}

fn text(value: &str) -> graph::Value {
    graph::Value {
        kind: Some(graph::value::Kind::Text(value.to_owned())),
    }
}

fn integer(value: i64) -> graph::Value {
    graph::Value {
        kind: Some(graph::value::Kind::Integer(value)),
    }
}

fn field(key: &str, value: graph::Value) -> graph::Field {
    graph::Field {
        key: key.to_owned(),
        value: Some(value),
    }
}

fn text_list(values: impl IntoIterator<Item = String>) -> graph::Value {
    graph::Value {
        kind: Some(graph::value::Kind::List(graph::ListValue {
            values: values.into_iter().map(|value| text(&value)).collect(),
        })),
    }
}

fn stable_id(kind: &str, file: &str, offset: u32, end: u32, spelling: &str) -> String {
    let raw = format!("{file}\0{offset}\0{end}\0{spelling}");
    let mut digest = Sha256::new();
    digest.update(b"v2\0frontend\0clang-c\0");
    digest.update(kind.as_bytes());
    digest.update(b"\0");
    digest.update(raw.as_bytes());
    let hex = format!("{:x}", digest.finalize());
    format!("v2:frontend:clang-c:{kind}:{}", &hex[..20])
}

fn stable_id_parts(kind: &str, parts: &[String]) -> String {
    let raw = parts.join("\0");
    let mut digest = Sha256::new();
    digest.update(b"v2\0frontend\0clang-c\0");
    digest.update(kind.as_bytes());
    digest.update(b"\0");
    digest.update(raw.as_bytes());
    let hex = format!("{:x}", digest.finalize());
    format!("v2:frontend:clang-c:{kind}:{}", &hex[..20])
}

fn linkage_name(linkage: CXLinkageKind) -> &'static str {
    match linkage {
        CXLinkage_Internal => "internal",
        CXLinkage_External => "external",
        CXLinkage_UniqueExternal => "unique-external",
        CXLinkage_NoLinkage => "none",
        _ => "invalid",
    }
}

unsafe fn cx_string(value: CXString) -> String {
    let pointer = clang_getCString(value);
    let result = if pointer.is_null() {
        String::new()
    } else {
        CStr::from_ptr(pointer).to_string_lossy().into_owned()
    };
    clang_disposeString(value);
    result
}

unsafe fn cursor_file(cursor: CXCursor) -> (String, u32, u32, u32, u32, u32, u32) {
    let extent = clang_getCursorExtent(cursor);
    let location = clang_getRangeStart(extent);
    let mut file = ptr::null_mut();
    let mut line = 0;
    let mut column = 0;
    let mut offset = 0;
    clang_getSpellingLocation(location, &mut file, &mut line, &mut column, &mut offset);
    let filename = if file.is_null() {
        String::new()
    } else {
        cx_string(clang_getFileName(file))
    };

    let end_location = clang_getRangeEnd(extent);
    let mut end_file = ptr::null_mut();
    let mut end_line = 0;
    let mut end_column = 0;
    let mut end_offset = offset;
    clang_getSpellingLocation(
        end_location,
        &mut end_file,
        &mut end_line,
        &mut end_column,
        &mut end_offset,
    );
    (filename, line, column, offset, end_offset, end_line, end_column)
}

struct Emitter {
    nodes: File,
    edges: File,
    node_ids: FxHashSet<IdKey>,
    edge_ids: FxHashSet<(IdKey, IdKey, IdKey)>,
    node_count: u64,
    edge_count: u64,
    file_ids: FxHashMap<String, String>,
    root_files: FxHashSet<String>,
    slot_bindings: FxHashMap<String, FxHashSet<String>>,
    function_ids: FxHashMap<String, FxHashSet<String>>,
    function_definitions: FxHashMap<String, FxHashSet<String>>,
    function_declarations: FxHashMap<String, FxHashSet<String>>,
    function_parameters: FxHashMap<String, Vec<String>>,
    usr_ids: FxHashMap<String, String>,
    path_cache: FxHashMap<String, String>,
}

impl Emitter {
    fn canonical_file(&mut self, raw: String) -> String {
        if raw.is_empty() {
            return raw;
        }
        if let Some(cached) = self.path_cache.get(&raw) {
            return cached.clone();
        }
        let canonical = PathBuf::from(&raw)
            .canonicalize()
            .unwrap_or_else(|_| PathBuf::from(&raw))
            .to_string_lossy()
            .into_owned();
        self.path_cache.insert(raw, canonical.clone());
        canonical
    }

    fn node(&mut self, record: graph::NodeRecord) -> io::Result<()> {
        if !self.node_ids.insert(id_key(&record.id)) {
            return Ok(());
        }
        if record.kind == "function" {
            let declaration_only = record.properties.iter().find_map(|property| {
                if property.key != "declaration_only" {
                    return None;
                }
                match property.value.as_ref()?.kind.as_ref()? {
                    graph::value::Kind::Boolean(value) => Some(*value),
                    _ => None,
                }
            }).unwrap_or(false);
            self.function_ids
                .entry(record.label.clone())
                .or_default()
                .insert(record.id.clone());
            let index = if declaration_only {
                &mut self.function_declarations
            } else {
                &mut self.function_definitions
            };
            index.entry(record.label.clone()).or_default().insert(record.id.clone());
        }
        if record.kind == "parameter" {
            if let Some(owner) = record.properties.iter().find_map(|property| {
                if property.key != "owner_function_id" { return None; }
                match property.value.as_ref()?.kind.as_ref()? {
                    graph::value::Kind::Text(value) => Some(value.clone()),
                    _ => None,
                }
            }) {
                self.function_parameters.entry(owner).or_default().push(record.id.clone());
            }
        }
        frame(&mut self.nodes, &record.encode_to_vec())?;
        self.node_count += 1;
        Ok(())
    }

    fn edge(&mut self, record: graph::EdgeRecord) -> io::Result<()> {
        let key = (id_key(&record.kind), id_key(&record.source), id_key(&record.target));
        if !self.edge_ids.insert(key) {
            return Ok(());
        }
        frame(&mut self.edges, &record.encode_to_vec())?;
        self.edge_count += 1;
        Ok(())
    }
}

unsafe fn cursor_usr(cursor: CXCursor) -> String {
    cx_string(clang_getCursorUSR(cursor))
}

unsafe fn resolved_declaration_id(
    cursor: CXCursor,
    id_kind: &str,
    file: &str,
    offset: u32,
    end_offset: u32,
    spelling: &str,
    emitter: &Emitter,
) -> String {
    let usr = cursor_usr(cursor);
    emitter
        .usr_ids
        .get(&usr)
        .cloned()
        .unwrap_or_else(|| stable_id(id_kind, file, offset, end_offset, spelling))
}

fn emit_cross_tu_links(emitter: &mut Emitter) -> io::Result<()> {
    let definitions: Vec<(String, String)> = emitter
        .function_definitions
        .iter()
        .filter_map(|(name, ids)| {
            if ids.len() == 1 { Some((name.clone(), ids.iter().next()?.clone())) } else { None }
        })
        .collect();
    for (name, definition) in definitions {
        let declarations: Vec<String> = emitter
            .function_declarations
            .get(&name)
            .into_iter()
            .flat_map(|ids| ids.iter().cloned())
            .collect();
        for declaration in declarations {
            if declaration == definition {
                continue;
            }
            emitter.edge(graph::EdgeRecord {
                kind: "REFERS_TO".to_owned(), source: declaration, target: definition.clone(),
                properties: vec![field("reason", text("prototype-of"))], source_tier: "T1".to_owned(),
                relationship_class: "REFERS_TO".to_owned(),
            })?;
        }
    }
    Ok(())
}

fn emit_file_node(emitter: &mut Emitter, path: &str, source_dir: &str) -> io::Result<()> {
    let absolute = Path::new(path)
        .canonicalize()
        .unwrap_or_else(|_| PathBuf::from(path));
    let absolute_text = absolute.to_string_lossy().into_owned();
    let display = Path::new(&absolute_text)
        .strip_prefix(source_dir)
        .map(|value| value.to_string_lossy().into_owned())
        .unwrap_or_else(|_| absolute_text.clone());
    let bytes = fs::read(&absolute).unwrap_or_default();
    let mut digest = Sha256::new();
    digest.update(&bytes);
    let content_hash = format!("{:x}", digest.finalize());
    let lines = bytes.iter().filter(|byte| **byte == b'\n').count() as i64
        + if !bytes.is_empty() && !bytes.ends_with(b"\n") { 1 } else { 0 };
    let id = stable_id_parts("file", &[absolute_text.clone()]);
    emitter.file_ids.insert(absolute_text.clone(), id.clone());
    emitter.node(graph::NodeRecord {
        id,
        kind: "file".to_owned(),
        label: display.clone(),
        properties: vec![
            field("file", text(&display)),
            field("absolute_file", text(&absolute_text)),
            field("content_hash", text(&content_hash)),
            field("lines", integer(lines)),
            field("language", text("c")),
            field("provenance", text("project-root")),
            field("is_external", graph::Value { kind: Some(graph::value::Kind::Boolean(false)) }),
            field("is_system", graph::Value { kind: Some(graph::value::Kind::Boolean(false)) }),
            field("included_because", text("project-root")),
        ],
        tier: "T0".to_owned(),
    })
}

fn emit_macros_for_file(emitter: &mut Emitter, path: &str) -> io::Result<()> {
    let bytes = fs::read(path).unwrap_or_default();
    let source = String::from_utf8_lossy(&bytes);
    let file_id = match emitter.file_ids.get(path) {
        Some(id) => id.clone(),
        None => return Ok(()),
    };
    let mut line_offset = 0u32;
    for line in source.split_inclusive('\n') {
        let without_newline = line.strip_suffix('\n').unwrap_or(line);
        let leading = without_newline.len() - without_newline.trim_start().len();
        let definition = without_newline[leading..].strip_prefix("#define");
        if let Some(definition) = definition {
            let definition = definition.trim_start();
            let name_end = definition
                .find(|character: char| !(character == '_' || character.is_ascii_alphanumeric()))
                .unwrap_or(definition.len());
            if name_end == 0 {
                line_offset = line_offset.saturating_add(line.len() as u32);
                continue;
            }
            let name = &definition[..name_end];
            let mut rest = &definition[name_end..];
            let mut parameters = Vec::new();
            let form = if rest.starts_with('(') {
                if let Some(close) = rest.find(')') {
                    parameters.extend(
                        rest[1..close]
                            .split(',')
                            .map(str::trim)
                            .filter(|value| !value.is_empty())
                            .map(str::to_owned),
                    );
                    rest = &rest[close + 1..];
                    "function-like"
                } else {
                    "object-like"
                }
            } else {
                "object-like"
            };
            let body = rest.trim().to_owned();
            let macro_id = stable_id_parts(
                "macro",
                &[path.to_owned(), line_offset.to_string(), name.to_owned()],
            );
            let signature = if form == "function-like" {
                format!("{}({})", name, parameters.join(", "))
            } else {
                name.to_owned()
            };
            let end_column = without_newline.len().max(1) as i64;
            emitter.node(graph::NodeRecord {
                id: macro_id.clone(), kind: "macro".to_owned(), label: name.to_owned(),
                properties: vec![
                    field("file", text(path)), field("absolute_file", text(path)),
                    field("start_offset", integer(line_offset as i64)),
                    field("end_offset", integer(line_offset as i64 + without_newline.len() as i64)),
                    field("start_line", integer(source[..line_offset as usize].bytes().filter(|b| *b == b'\n').count() as i64 + 1)),
                    field("start_column", integer(leading as i64 + 1)),
                    field("end_line", integer(source[..line_offset as usize].bytes().filter(|b| *b == b'\n').count() as i64 + 1)),
                    field("end_column", integer(end_column)), field("syntax_kind", text("macro")),
                    field("form", text(form)), field("parameters", text_list(parameters)),
                    field("body", text(&body)), field("signature", text(&signature)),
                ], tier: "T1".to_owned(),
            })?;
            emitter.edge(graph::EdgeRecord {
                kind: "DECLARES".to_owned(), source: file_id.clone(), target: macro_id,
                properties: Vec::new(), source_tier: "T0".to_owned(),
                relationship_class: "DECLARES".to_owned(),
            })?;
        }
        line_offset = line_offset.saturating_add(line.len() as u32);
    }
    Ok(())
}

extern "C" fn visit(cursor: CXCursor, parent: CXCursor, data: CXClientData) -> CXChildVisitResult {
    unsafe {
        let emitter = &mut *(data as *mut Emitter);
        if let Err(error) = visit_one(cursor, parent, emitter) {
            eprintln!("native clang frontend: {error}");
            return CXChildVisit_Break;
        }
    }
    CXChildVisit_Recurse
}

struct ReferenceProbe {
    cursor: Option<CXCursor>,
}

struct ChildProbe {
    cursors: Vec<CXCursor>,
}

extern "C" fn collect_direct_child(
    cursor: CXCursor,
    _parent: CXCursor,
    data: CXClientData,
) -> CXChildVisitResult {
    unsafe { (&mut *(data as *mut ChildProbe)).cursors.push(cursor); }
    CXChildVisit_Continue
}

struct BindingProbe {
    fields: Vec<String>,
    functions: Vec<String>,
}

extern "C" fn collect_binding_reference(
    cursor: CXCursor,
    _parent: CXCursor,
    data: CXClientData,
) -> CXChildVisitResult {
    unsafe {
        let probe = &mut *(data as *mut BindingProbe);
        let kind = clang_getCursorKind(cursor);
        if kind == CXCursor_MemberRef || kind == CXCursor_MemberRefExpr || kind == CXCursor_DeclRefExpr {
            let referenced = clang_getCursorReferenced(cursor);
            if clang_is_null(referenced) == 0 {
                let referenced_kind = clang_getCursorKind(referenced);
                let name = cx_string(clang_getCursorSpelling(referenced));
                if referenced_kind == CXCursor_FieldDecl {
                    probe.fields.push(name);
                } else if referenced_kind == CXCursor_FunctionDecl {
                    probe.functions.push(name);
                }
            }
        }
    }
    CXChildVisit_Recurse
}

extern "C" fn collect_callee_reference(
    cursor: CXCursor,
    _parent: CXCursor,
    data: CXClientData,
) -> CXChildVisitResult {
    unsafe {
        let probe = &mut *(data as *mut ReferenceProbe);
        let kind = clang_getCursorKind(cursor);
        if kind == CXCursor_DeclRefExpr || kind == CXCursor_MemberRef || kind == CXCursor_MemberRefExpr {
            probe.cursor = Some(cursor);
            return CXChildVisit_Break;
        }
    }
    CXChildVisit_Recurse
}

extern "C" fn collect_parameter_reference(
    cursor: CXCursor,
    _parent: CXCursor,
    data: CXClientData,
) -> CXChildVisitResult {
    unsafe {
        let probe = &mut *(data as *mut ReferenceProbe);
        let referenced = clang_getCursorReferenced(cursor);
        let kind = if clang_is_null(referenced) == 0 {
            clang_getCursorKind(referenced)
        } else {
            clang_getCursorKind(cursor)
        };
        if kind == CXCursor_ParmDecl {
            probe.cursor = Some(if clang_is_null(referenced) == 0 { referenced } else { cursor });
            return CXChildVisit_Break;
        }
    }
    CXChildVisit_Recurse
}

extern "C" fn collect_inclusion(
    included_file: CXFile,
    inclusion_stack: *mut CXSourceLocation,
    include_len: c_uint,
    data: CXClientData,
) {
    unsafe {
        let emitter = &mut *(data as *mut Emitter);
        if included_file.is_null() || inclusion_stack.is_null() || include_len == 0 {
            return;
        }
        let included_path = emitter.canonical_file(cx_string(clang_getFileName(included_file)));
        let mut source_file = ptr::null_mut();
        clang_getFileLocation(
            *inclusion_stack.add((include_len - 1) as usize),
            &mut source_file,
            ptr::null_mut(),
            ptr::null_mut(),
            ptr::null_mut(),
        );
        if source_file.is_null() {
            return;
        }
        let source_path = emitter.canonical_file(cx_string(clang_getFileName(source_file)));
        let (Some(source), Some(target)) = (
            emitter.file_ids.get(&source_path).cloned(),
            emitter.file_ids.get(&included_path).cloned(),
        ) else {
            return;
        };
        if let Err(error) = emitter.edge(graph::EdgeRecord {
            kind: "DEPENDS_ON".to_owned(),
            source,
            target,
            properties: vec![field("directive", text("#include"))],
            source_tier: "T0".to_owned(),
            relationship_class: "DEPENDS_ON".to_owned(),
        }) {
            eprintln!("native clang inclusion emission failed: {error}");
        }
    }
}

unsafe fn function_reference_id(cursor: CXCursor, emitter: &mut Emitter) -> Option<String> {
    let direct = clang_getCursorReferenced(cursor);
    let mut probe = ReferenceProbe { cursor: None };
    if clang_is_null(direct) != 0 {
        clang_visitChildren(
            cursor,
            collect_callee_reference,
            &mut probe as *mut ReferenceProbe as *mut c_void,
        );
    }
    let Some(referenced) = (if clang_is_null(direct) == 0 {
        Some(direct)
    } else {
        probe.cursor
    }) else {
        return None;
    };
    if clang_is_null(referenced) != 0 {
        return None;
    }
    let target_kind = cx_string(clang_getCursorKindSpelling(clang_getCursorKind(referenced)));
    if target_kind != "FunctionDecl" {
        return None;
    }
    let target_name = cx_string(clang_getCursorSpelling(referenced));
    let (raw_file, _, _, target_offset, target_end, _, _) = cursor_file(referenced);
    let target_file = emitter.canonical_file(raw_file);
    if target_file.is_empty() {
        return None;
    }
    Some(resolved_declaration_id(
        referenced, "function", &target_file, target_offset, target_end,
        &target_name, emitter,
    ))
}

unsafe fn referenced_target_id(cursor: CXCursor, emitter: &mut Emitter) -> Option<(String, String)> {
    let direct = clang_getCursorReferenced(cursor);
    let mut probe = ReferenceProbe { cursor: None };
    if clang_is_null(direct) != 0 {
        clang_visitChildren(
            cursor,
            collect_callee_reference,
            &mut probe as *mut ReferenceProbe as *mut c_void,
        );
    }
    let Some(referenced) = (if clang_is_null(direct) == 0 {
        Some(direct)
    } else {
        probe.cursor
    }) else {
        return None;
    };
    if clang_is_null(referenced) != 0 {
        return None;
    }
    let target_kind = cx_string(clang_getCursorKindSpelling(clang_getCursorKind(referenced)));
    let id_kind = match target_kind.as_str() {
        "FunctionDecl" => "function",
        "VarDecl" | "ParmVarDecl" | "ParmDecl" | "FieldDecl" => "value",
        _ => return None,
    };
    let target_name = cx_string(clang_getCursorSpelling(referenced));
    let (raw_file, _, _, target_offset, target_end, _, _) = cursor_file(referenced);
    let target_file = emitter.canonical_file(raw_file);
    if target_file.is_empty() {
        return None;
    }
    Some((
        target_kind,
        resolved_declaration_id(
            referenced, id_kind, &target_file, target_offset, target_end,
            &target_name, emitter,
        ),
    ))
}

unsafe fn parameter_reference_id(cursor: CXCursor, emitter: &mut Emitter) -> Option<String> {
    let direct = clang_getCursorReferenced(cursor);
    let direct_kind = if clang_is_null(direct) == 0 {
        clang_getCursorKind(direct)
    } else {
        CXCursor_InvalidFile
    };
    let referenced = if direct_kind == CXCursor_ParmDecl {
        direct
    } else {
        let mut probe = ReferenceProbe { cursor: None };
        clang_visitChildren(
            cursor,
            collect_parameter_reference,
            &mut probe as *mut ReferenceProbe as *mut c_void,
        );
        probe.cursor?
    };
    let target_name = cx_string(clang_getCursorSpelling(referenced));
    let (raw_file, _, _, target_offset, target_end, _, _) = cursor_file(referenced);
    let target_file = emitter.canonical_file(raw_file);
    if target_file.is_empty() {
        return None;
    }
    Some(resolved_declaration_id(
        referenced, "value", &target_file, target_offset, target_end,
        &target_name, emitter,
    ))
}

unsafe fn visit_one(cursor: CXCursor, parent: CXCursor, emitter: &mut Emitter) -> io::Result<()> {
    let syntax_kind = cx_string(clang_getCursorKindSpelling(clang_getCursorKind(cursor)));
    let spelling = cx_string(clang_getCursorSpelling(cursor));
    let (raw_file, line, column, offset, end_offset, end_line, end_column) = cursor_file(cursor);
    let file = emitter.canonical_file(raw_file);
    if file.is_empty() || (!emitter.root_files.is_empty() && !emitter.root_files.contains(&file)) {
        return Ok(());
    }
    if syntax_kind == "InclusionDirective" {
        let included = clang_getIncludedFile(cursor);
        if !included.is_null() {
            let included_raw = cx_string(clang_getFileName(included));
            let included_file = emitter.canonical_file(included_raw);
            if let (Some(source_id), Some(target_id)) = (
                emitter.file_ids.get(&file).cloned(),
                emitter.file_ids.get(&included_file).cloned(),
            ) {
                emitter.edge(graph::EdgeRecord {
                    kind: "DEPENDS_ON".to_owned(), source: source_id, target: target_id,
                    properties: vec![field("directive", text("#include"))],
                    source_tier: "T0".to_owned(), relationship_class: "DEPENDS_ON".to_owned(),
                })?;
            }
        }
        return Ok(());
    }

    let (node_kind, tier, id) = if let Some(mapped_kind) = match syntax_kind.as_str() {
        "FunctionDecl" => Some("function"),
        "RecordDecl" | "StructDecl" | "UnionDecl" => Some("record"),
        "EnumDecl" => Some("enum"),
        "TypedefDecl" => Some("type"),
        "ParmVarDecl" | "ParmDecl" => Some("parameter"),
        "VarDecl" => Some("variable"),
        "FieldDecl" => Some("property"),
        "EnumConstantDecl" => Some("constant"),
        _ => None,
    } {
        let id_kind = if matches!(syntax_kind.as_str(), "ParmVarDecl" | "VarDecl" | "FieldDecl" | "EnumConstantDecl") {
            "value"
        } else {
            mapped_kind
        };
        (
            mapped_kind.to_owned(),
            if id_kind == "value" { "T2" } else { "T1" }.to_owned(),
            stable_id(id_kind, &file, offset, end_offset, &spelling),
        )
    } else if syntax_kind == "CallExpr"
        || syntax_kind.ends_with("Stmt")
        || syntax_kind.ends_with("Expr")
        || syntax_kind.ends_with("Operator")
        || matches!(syntax_kind.as_str(), "IntegerLiteral" | "StringLiteral" | "CharacterLiteral")
    {
        (
            if syntax_kind == "CallExpr" { "call" } else if syntax_kind.ends_with("Stmt") { "statement" } else { "expression" }.to_owned(),
            "T3".to_owned(),
            stable_id("body", &file, offset, end_offset, &syntax_kind),
        )
    } else {
        return Ok(());
    };

    let type_spelling = cx_string(clang_getTypeSpelling(clang_getCursorType(cursor)));
    let operator = spelling.clone();
    let mut properties = vec![
        field("file", text(&file)),
        field("absolute_file", text(&file)),
        field("start_offset", integer(offset as i64)),
        field("end_offset", integer(end_offset as i64)),
        field("start_line", integer(line as i64)),
        field("start_column", integer(column as i64)),
        field("end_line", integer(end_line as i64)),
        field("end_column", integer(end_column as i64)),
        field("syntax_kind", text(&syntax_kind)),
        field("type", text(&type_spelling)),
    ];
    let owner_id = function_owner(cursor, emitter);
    if matches!(
        syntax_kind.as_str(),
        "FunctionDecl"
            | "RecordDecl"
            | "StructDecl"
            | "UnionDecl"
            | "EnumDecl"
            | "TypedefDecl"
            | "ParmVarDecl"
            | "ParmDecl"
            | "VarDecl"
            | "FieldDecl"
            | "EnumConstantDecl"
    ) {
        let usr = cursor_usr(cursor);
        if !usr.is_empty() {
            emitter.usr_ids.entry(usr).or_insert_with(|| id.clone());
        }
    }
    if let Some(owner_id) = &owner_id {
        properties.push(field("owner_function_id", text(owner_id)));
    }
    if syntax_kind == "FunctionDecl" {
        let has_definition = clang_isCursorDefinition(cursor) != 0;
        properties.push(field("declaration_only", graph::Value {
            kind: Some(graph::value::Kind::Boolean(!has_definition)),
        }));
        properties.push(field("form", text("function")));
        // Keep linkage on every function entity, including internal/static
        // functions.  Export status is a separate graph relationship; using
        // it as the function identity would make compiler-visible helpers
        // disappear from downstream resolution.
        properties.push(field(
            "linkage",
            text(linkage_name(clang_getCursorLinkage(cursor))),
        ));
    }
    let mut call_target = None;
    if syntax_kind == "CallExpr" {
        let direct = clang_getCursorReferenced(cursor);
        let mut probe = ReferenceProbe { cursor: None };
        if clang_is_null(direct) != 0 {
            clang_visitChildren(cursor, collect_callee_reference, &mut probe as *mut ReferenceProbe as *mut c_void);
        }
        let referenced = if clang_is_null(direct) == 0 { Some(direct) } else { probe.cursor };
        if let Some(referenced) = referenced.filter(|referenced| clang_is_null(*referenced) == 0) {
            let target_kind = cx_string(clang_getCursorKindSpelling(clang_getCursorKind(referenced)));
            let target_name = cx_string(clang_getCursorSpelling(referenced));
            let (target_raw_file, _, _, target_offset, target_end, _, _) = cursor_file(referenced);
            let target_file = emitter.canonical_file(target_raw_file);
            if !target_file.is_empty() {
                let target_id_kind = match target_kind.as_str() {
                    "FunctionDecl" => Some("function"),
                    "VarDecl" | "ParmVarDecl" | "ParmDecl" | "FieldDecl" => Some("value"),
                    _ => None,
                };
                if let Some(target_id_kind) = target_id_kind {
                    let target_id = resolved_declaration_id(
                        referenced, target_id_kind, &target_file, target_offset,
                        target_end, &target_name, emitter,
                    );
                    properties.push(field("callee", text(&target_name)));
                    if target_kind == "FieldDecl" {
                        properties.push(field("receiver_member_id", text(&target_id)));
                        properties.push(field("resolution", text("function-pointer")));
                        emitter.edge(graph::EdgeRecord {
                            kind: "READS_CALLEE".to_owned(), source: id.clone(), target: target_id,
                            properties: Vec::new(), source_tier: tier.clone(),
                            relationship_class: "READS_CALLEE".to_owned(),
                        })?;
                        let targets: Vec<String> = emitter
                            .slot_bindings
                            .get(&target_name)
                            .into_iter()
                            .flat_map(|ids| ids.iter().cloned())
                            .collect();
                        for target in targets {
                            emitter.edge(graph::EdgeRecord {
                                kind: "MAY_INVOKE".to_owned(), source: id.clone(), target,
                                properties: vec![field("resolution", text("binding"))],
                                source_tier: tier.clone(), relationship_class: "MAY_INVOKE".to_owned(),
                            })?;
                        }
                    } else if target_kind == "FunctionDecl" {
                        properties.push(field("primary_target_id", text(&target_id)));
                        properties.push(field("resolution", text("exact")));
                        call_target = Some(target_id.clone());
                        emitter.edge(graph::EdgeRecord {
                            kind: "INVOKES".to_owned(), source: id.clone(), target: target_id,
                            properties: Vec::new(), source_tier: tier.clone(),
                            relationship_class: "INVOKES".to_owned(),
                        })?;
                    }
                }
            }
        }
    }
    emitter.node(graph::NodeRecord {
        id: id.clone(),
        kind: node_kind.clone(),
        label: if spelling.is_empty() { syntax_kind.clone() } else { spelling },
        properties,
        tier: tier.clone(),
    })?;

    if syntax_kind == "VarDecl" {
        let mut probe = BindingProbe { fields: Vec::new(), functions: Vec::new() };
        clang_visitChildren(cursor, collect_binding_reference, &mut probe as *mut BindingProbe as *mut c_void);
        if !probe.fields.is_empty() && !probe.functions.is_empty() {
            let function_ids: Vec<String> = probe
                .functions
                .iter()
                .flat_map(|name| emitter.function_ids.get(name).into_iter().flat_map(|ids| ids.iter().cloned()))
                .collect();
            for field_name in &probe.fields {
                let targets = {
                    let slots = emitter.slot_bindings.entry(field_name.clone()).or_default();
                    for target in &function_ids {
                        slots.insert(target.clone());
                    }
                    slots.iter().cloned().collect::<Vec<_>>()
                };
                for target in targets {
                    emitter.edge(graph::EdgeRecord {
                        kind: "MAY_INVOKE".to_owned(), source: id.clone(), target,
                        properties: vec![field("resolution", text("registration")), field("slot", text(field_name))],
                        source_tier: tier.clone(), relationship_class: "MAY_INVOKE".to_owned(),
                    })?;
                }
            }
        }
    }

    if tier == "T3" || syntax_kind == "VarDecl" {
        let mut children = ChildProbe { cursors: Vec::new() };
        clang_visitChildren(cursor, collect_direct_child, &mut children as *mut ChildProbe as *mut c_void);
        let child_ids: Vec<String> = children
            .cursors
            .iter()
            .filter_map(|child| cursor_graph_id(*child, emitter))
            .collect();
        if syntax_kind == "CallExpr" {
            let arguments: Vec<String> = child_ids.iter().skip(1).cloned().collect();
            let target_parameters = call_target.as_ref()
                .and_then(|target| emitter.function_parameters.get(target))
                .cloned()
                .unwrap_or_default();
            for (position, argument_id) in arguments.iter().enumerate() {
                emitter.edge(graph::EdgeRecord {
                    kind: "HAS_ARGUMENT".to_owned(), source: id.clone(), target: argument_id.clone(),
                    properties: vec![field("position", integer(position as i64))],
                    source_tier: tier.clone(), relationship_class: "HAS_ARGUMENT".to_owned(),
                })?;
                if let Some(argument_cursor) = children.cursors.get(position + 1) {
                    if let Some(callback_id) = function_reference_id(*argument_cursor, emitter) {
                        emitter.edge(graph::EdgeRecord {
                            kind: "PASSES_CALLBACK".to_owned(), source: id.clone(), target: callback_id,
                            properties: vec![field("position", integer(position as i64))],
                            source_tier: tier.clone(), relationship_class: "PASSES_CALLBACK".to_owned(),
                        })?;
                    }
                }
                if let Some(parameter_id) = target_parameters.get(position) {
                    emitter.edge(graph::EdgeRecord {
                        kind: "ARGUMENT_BINDS_PARAMETER".to_owned(), source: argument_id.clone(), target: parameter_id.clone(),
                        properties: vec![field("position", integer(position as i64)), field("callsite", text(&id))],
                        source_tier: tier.clone(), relationship_class: "ARGUMENT_BINDS_PARAMETER".to_owned(),
                    })?;
                    emitter.edge(graph::EdgeRecord {
                        kind: "VALUE_FLOWS_TO".to_owned(), source: argument_id.clone(), target: parameter_id.clone(),
                        properties: vec![field("reason", text("call-argument")), field("callsite", text(&id))],
                        source_tier: tier.clone(), relationship_class: "VALUE_FLOWS_TO".to_owned(),
                    })?;
                }
            }
        } else if syntax_kind == "ReturnStmt" {
            if let (Some(value_id), Some(owner)) = (child_ids.first(), owner_id.clone()) {
                emitter.edge(graph::EdgeRecord {
                    kind: "RETURNS_VALUE".to_owned(), source: value_id.clone(), target: owner,
                    properties: Vec::new(), source_tier: tier.clone(), relationship_class: "RETURNS_VALUE".to_owned(),
                })?;
            }
        } else if matches!(syntax_kind.as_str(), "BinaryOperator" | "CompoundAssignOperator")
            && matches!(operator.as_str(), "=" | "+=" | "-=" | "*=" | "/=" | "%=" | "&=" | "|=" | "^=" | "<<=" | ">>=")
            && children.cursors.len() >= 2 {
            let left = child_ids.first().cloned();
            let right = child_ids.get(1).cloned();
            if let (Some(left), Some(right)) = (left, right) {
                emitter.edge(graph::EdgeRecord {
                    kind: "VALUE_FLOWS_TO".to_owned(), source: right.clone(), target: left.clone(),
                    properties: vec![field("reason", text("assignment"))],
                    source_tier: tier.clone(), relationship_class: "VALUE_FLOWS_TO".to_owned(),
                })?;
                if operator == "=" {
                    let left_reference = children
                        .cursors
                        .first()
                        .and_then(|child| referenced_target_id(*child, emitter));
                    let right_reference = children
                        .cursors
                        .get(1)
                        .and_then(|child| referenced_target_id(*child, emitter));
                    if let (Some((left_kind, left_target)), Some((right_kind, right_target))) =
                        (left_reference, right_reference)
                    {
                        if left_kind == "FieldDecl" {
                            let receiver_id = children
                                .cursors
                                .first()
                                .and_then(|child| parameter_reference_id(*child, emitter));
                            emitter.edge(graph::EdgeRecord {
                                kind: "VALUE_FLOWS_TO".to_owned(), source: left.clone(), target: left_target.clone(),
                                properties: vec![field("reason", text("field-write")), field("confidence", text("conservative"))],
                                source_tier: tier.clone(), relationship_class: "VALUE_FLOWS_TO".to_owned(),
                            })?;
                            if let Some(owner) = owner_id.as_ref() {
                                let parameters = emitter.function_parameters.get(owner).cloned().unwrap_or_default();
                                let receiver_position = receiver_id
                                    .as_ref()
                                    .and_then(|id| parameters.iter().position(|item| item == id));
                                let value_position = parameters.iter().position(|id| id == &right_target);
                                if let (Some(receiver_position), Some(value_position)) =
                                    (receiver_position, value_position)
                                {
                                    emitter.edge(graph::EdgeRecord {
                                        kind: "WRITES_PARAMETER_PROPERTY".to_owned(), source: owner.clone(), target: left_target,
                                        properties: vec![
                                            field("receiver_position", integer(receiver_position as i64)),
                                            field("value_position", integer(value_position as i64)),
                                        ], source_tier: "T1".to_owned(), relationship_class: "WRITES_PARAMETER_PROPERTY".to_owned(),
                                    })?;
                                }
                            }
                        }
                        let _ = right_kind;
                    }
                }
            }
        } else if matches!(syntax_kind.as_str(), "UnaryOperator" | "ConditionalOperator") || syntax_kind == "BinaryOperator" && !child_ids.is_empty() {
            let operand_start = if syntax_kind == "ConditionalOperator" { 1 } else { 0 };
            for operand in child_ids.iter().skip(operand_start) {
                emitter.edge(graph::EdgeRecord {
                    kind: "VALUE_FLOWS_TO".to_owned(), source: operand.clone(), target: id.clone(),
                    properties: vec![field("reason", text("arithmetic-operand"))],
                    source_tier: tier.clone(), relationship_class: "VALUE_FLOWS_TO".to_owned(),
                })?;
            }
        } else if syntax_kind == "VarDecl" {
            if let (Some(initializer), Some(variable)) = (child_ids.last(), Some(id.clone())) {
                emitter.edge(graph::EdgeRecord {
                    kind: "VALUE_FLOWS_TO".to_owned(), source: initializer.clone(), target: variable,
                    properties: vec![field("reason", text("initializer"))],
                    source_tier: "T2".to_owned(), relationship_class: "VALUE_FLOWS_TO".to_owned(),
                })?;
            }
        }
    }

    if syntax_kind == "CallExpr" {
        if let (Some(owner_id), Some(target_id)) = (owner_id.clone(), call_target) {
            emitter.edge(graph::EdgeRecord {
                kind: "CALLS".to_owned(), source: owner_id, target: target_id,
                properties: Vec::new(), source_tier: "T1".to_owned(),
                relationship_class: "CALLS".to_owned(),
            })?;
        }
    } else if matches!(
        syntax_kind.as_str(),
        "ImplicitCastExpr"
            | "CStyleCastExpr"
            | "CXXStaticCastExpr"
            | "CXXReinterpretCastExpr"
            | "CXXConstCastExpr"
            | "CXXFunctionalCastExpr"
            | "ParenExpr"
            | "ExprWithCleanups"
            | "MaterializeTemporaryExpr"
            | "ConstantExpr"
    ) {
        if let Some(child_id) = child_ids_for_value_preserving(cursor, emitter) {
            emitter.edge(graph::EdgeRecord {
                kind: "VALUE_FLOWS_TO".to_owned(), source: child_id, target: id.clone(),
                properties: vec![field("reason", text("value-preserving-expression"))],
                source_tier: tier.clone(), relationship_class: "VALUE_FLOWS_TO".to_owned(),
            })?;
        }
    } else if matches!(syntax_kind.as_str(), "DeclRefExpr" | "MemberRefExpr" | "MemberRef") {
        let referenced = clang_getCursorReferenced(cursor);
        if clang_is_null(referenced) == 0 {
            let target_kind = cx_string(clang_getCursorKindSpelling(clang_getCursorKind(referenced)));
            let target_name = cx_string(clang_getCursorSpelling(referenced));
            let (target_raw_file, _, _, target_offset, target_end, _, _) = cursor_file(referenced);
            let target_file = emitter.canonical_file(target_raw_file);
            let id_kind = match target_kind.as_str() {
                "FunctionDecl" => Some("function"),
                "VarDecl" | "ParmVarDecl" | "ParmDecl" | "FieldDecl" => Some("value"),
                _ => None,
            };
            if let (Some(id_kind), Some(_owner_id)) = (id_kind, owner_id.as_ref()) {
                let target_id = resolved_declaration_id(
                    referenced, id_kind, &target_file, target_offset, target_end,
                    &target_name, emitter,
                );
                emitter.edge(graph::EdgeRecord {
                    kind: "REFERS_TO".to_owned(), source: id.clone(), target: target_id.clone(),
                    properties: Vec::new(), source_tier: tier.clone(), relationship_class: "REFERS_TO".to_owned(),
                })?;
                emitter.edge(graph::EdgeRecord {
                    kind: "VALUE_FLOWS_TO".to_owned(), source: target_id, target: id.clone(),
                    properties: vec![field("reason", text("read"))], source_tier: tier.clone(),
                    relationship_class: "VALUE_FLOWS_TO".to_owned(),
                })?;
            }
        }
    }

    let (parent_raw_file, _parent_line, _parent_column, parent_offset, parent_end, _, _) = cursor_file(parent);
    let parent_file = emitter.canonical_file(parent_raw_file);
    let parent_kind = cx_string(clang_getCursorKindSpelling(clang_getCursorKind(parent)));
    let parent_spelling = cx_string(clang_getCursorSpelling(parent));
    if let Some((_parent_kind, parent_tier, parent_id)) = cursor_identity(
        &parent_kind, &parent_file, parent_offset, parent_end, &parent_spelling,
    ) {
        let edge_kind = if node_kind == "function" || node_kind == "record" || node_kind == "enum" || node_kind == "type" {
            "DECLARES"
        } else if node_kind == "parameter" || node_kind == "variable" || node_kind == "property" || node_kind == "constant" {
            "DECLARES_VALUE"
        } else if tier == "T3" && parent_tier == "T1" {
            "CONTAINS_BODY"
        } else {
            "AST_CHILD"
        };
        emitter.edge(graph::EdgeRecord {
            kind: edge_kind.to_owned(),
            source: parent_id,
            target: id.clone(),
            properties: Vec::new(),
            source_tier: parent_tier,
            relationship_class: edge_kind.to_owned(),
        })?;
    } else if let Some(file_id) = emitter.file_ids.get(&file) {
        let edge_kind = if tier == "T3" { "CONTAINS_BODY" } else if node_kind == "parameter" || node_kind == "variable" || node_kind == "property" || node_kind == "constant" { "DECLARES_VALUE" } else { "DECLARES" };
        emitter.edge(graph::EdgeRecord {
            kind: edge_kind.to_owned(), source: file_id.clone(), target: id.clone(),
            properties: Vec::new(), source_tier: "T0".to_owned(), relationship_class: edge_kind.to_owned(),
        })?;
    }

    if syntax_kind == "FunctionDecl"
        && owner_id.is_none()
        && clang_isCursorDefinition(cursor) != 0
        && clang_getCursorLinkage(cursor) != CXLinkage_Internal
        && clang_getCursorLinkage(cursor) != CXLinkage_NoLinkage
    {
        if let Some(file_id) = emitter.file_ids.get(&file) {
            emitter.edge(graph::EdgeRecord {
                kind: "EXPORTS".to_owned(), source: file_id.clone(), target: id.clone(),
                properties: vec![field("name", text(&label_for_cursor(cursor)))],
                source_tier: "T0".to_owned(), relationship_class: "EXPORTS".to_owned(),
            })?;
        }
    }
    Ok(())
}

unsafe fn child_ids_for_value_preserving(cursor: CXCursor, emitter: &mut Emitter) -> Option<String> {
    let mut children = ChildProbe { cursors: Vec::new() };
    clang_visitChildren(
        cursor,
        collect_direct_child,
        &mut children as *mut ChildProbe as *mut c_void,
    );
    children
        .cursors
        .first()
        .and_then(|child| cursor_graph_id(*child, emitter))
}

unsafe fn cursor_graph_id(cursor: CXCursor, emitter: &mut Emitter) -> Option<String> {
    let syntax_kind = cx_string(clang_getCursorKindSpelling(clang_getCursorKind(cursor)));
    let spelling = cx_string(clang_getCursorSpelling(cursor));
    let (raw_file, _, _, offset, end_offset, _, _) = cursor_file(cursor);
    let file = emitter.canonical_file(raw_file);
    cursor_identity(&syntax_kind, &file, offset, end_offset, &spelling).map(|(_, _, id)| id)
}

unsafe fn label_for_cursor(cursor: CXCursor) -> String {
    cx_string(clang_getCursorSpelling(cursor))
}

unsafe fn function_owner(cursor: CXCursor, emitter: &mut Emitter) -> Option<String> {
    let mut current = clang_getCursorSemanticParent(cursor);
    for _ in 0..32 {
        let (raw_file, _, _, offset, end_offset, _, _) = cursor_file(current);
        let file = emitter.canonical_file(raw_file);
        if file.is_empty() || clang_is_null(current) != 0 {
            return None;
        }
        let syntax_kind = cx_string(clang_getCursorKindSpelling(clang_getCursorKind(current)));
        let spelling = cx_string(clang_getCursorSpelling(current));
        if syntax_kind == "FunctionDecl" {
            return Some(stable_id("function", &file, offset, end_offset, &spelling));
        }
        let next = clang_getCursorSemanticParent(current);
        if clang_is_null(next) != 0 {
            return None;
        }
        current = next;
    }
    None
}

unsafe fn clang_is_null(cursor: CXCursor) -> c_int {
    (clang_sys::clang_equalCursors(cursor, clang_sys::clang_getNullCursor()) != 0) as c_int
}

fn cursor_identity(
    syntax_kind: &str, file: &str, offset: u32, end_offset: u32, spelling: &str,
) -> Option<(String, String, String)> {
    if file.is_empty() {
        return None;
    }
    let (kind, tier, id_kind) = match syntax_kind {
        "FunctionDecl" => ("function", "T1", "function"),
        "RecordDecl" | "StructDecl" | "UnionDecl" => ("record", "T1", "record"),
        "EnumDecl" => ("enum", "T1", "enum"),
        "TypedefDecl" => ("type", "T1", "type"),
        "ParmVarDecl" | "ParmDecl" => ("parameter", "T2", "value"),
        "VarDecl" => ("variable", "T2", "value"),
        "FieldDecl" => ("property", "T2", "value"),
        "EnumConstantDecl" => ("constant", "T2", "value"),
        "CallExpr" => ("call", "T3", "body"),
        value if value.ends_with("Stmt") => ("statement", "T3", "body"),
        value if value.ends_with("Expr") || value.ends_with("Operator") => ("expression", "T3", "body"),
        "IntegerLiteral" | "StringLiteral" | "CharacterLiteral" => ("expression", "T3", "body"),
        _ => return None,
    };
    let identity = if id_kind == "body" { syntax_kind } else { spelling };
    Some((
        kind.to_owned(),
        tier.to_owned(),
        stable_id(id_kind, file, offset, end_offset, identity),
    ))
}

fn write_manifests(output: &Path, frontend_id: &str, node_count: u64, edge_count: u64) -> io::Result<()> {
    let manifest = graph::ShardManifest {
        format_version: SHARD_FORMAT_VERSION,
        frontend_id: frontend_id.to_owned(),
        shard_id: "0".to_owned(),
        node_count,
        edge_count,
        nodes_file: "nodes.pb".to_owned(),
        edges_file: "edges.pb".to_owned(),
    };
    let manifest_bytes = manifest.encode_to_vec();
    fs::write(output.join("manifest.pb"), manifest_bytes)?;
    let entry = graph::ShardSetEntry {
        shard_id: "0".to_owned(),
        directory: "shard-0".to_owned(),
        status: "complete".to_owned(),
        node_count,
        edge_count,
    };
    let set = graph::ShardSetManifest {
        format_version: SHARD_FORMAT_VERSION,
        frontend_id: frontend_id.to_owned(),
        shards: vec![entry],
    };
    fs::write(output.parent().unwrap_or(output).join("shards.pb"), set.encode_to_vec())
}

fn write_varint(file: &mut File, mut value: usize) -> io::Result<()> {
    while value > 0x7f {
        file.write_all(&[((value as u8) & 0x7f) | 0x80])?;
        value >>= 7;
    }
    file.write_all(&[value as u8])
}

fn write_delimited(file: &mut File, field_number: u32, payload: &[u8]) -> io::Result<()> {
    write_varint(file, ((field_number << 3) | 2) as usize)?;
    write_varint(file, payload.len())?;
    file.write_all(payload)
}

fn read_frame(file: &mut File) -> io::Result<Option<Vec<u8>>> {
    let mut header = [0u8; 4];
    match file.read_exact(&mut header) {
        Ok(()) => {
            let length = u32::from_be_bytes(header) as usize;
            let mut payload = vec![0u8; length];
            file.read_exact(&mut payload)?;
            Ok(Some(payload))
        }
        Err(error) if error.kind() == io::ErrorKind::UnexpectedEof => Ok(None),
        Err(error) => Err(error),
    }
}

fn has_property(properties: &[graph::Field], key: &str) -> bool {
    properties.iter().any(|property| property.key == key)
}

fn property_text(properties: &[graph::Field], key: &str) -> Option<String> {
    properties.iter().find_map(|property| {
        if property.key != key {
            return None;
        }
        match property.value.as_ref()?.kind.as_ref()? {
            graph::value::Kind::Text(value) => Some(value.clone()),
            _ => None,
        }
    })
}

fn add_contract_defaults(
    properties: &mut Vec<graph::Field>, frontend_id: &str, source_node: bool,
) {
    if !has_property(properties, "fact_origin") {
        properties.push(field("fact_origin", text("compiler")));
    }
    if !has_property(properties, "confidence") {
        properties.push(field("confidence", text("exact")));
    }
    if !source_node {
        return;
    }
    if !has_property(properties, "frontend_id") {
        properties.push(field("frontend_id", text(frontend_id)));
    }
    if !has_property(properties, "compiler_node_id") {
        properties.push(field("compiler_node_id", text(frontend_id)));
    }
    if !has_property(properties, "language") {
        properties.push(field("language", text("c")));
    }
    if !has_property(properties, "absolute_file") {
        let file = property_text(properties, "file").unwrap_or_default();
        properties.push(field("absolute_file", text(&file)));
    }
    if !has_property(properties, "content_hash") {
        properties.push(field("content_hash", text("")));
    }
    for key in [
        "start_offset", "end_offset", "start_line", "start_column",
        "end_line", "end_column",
    ] {
        if !has_property(properties, key) {
            properties.push(field(key, integer(0)));
        }
    }
}

fn object(fields: Vec<graph::Field>) -> graph::Value {
    graph::Value {
        kind: Some(graph::value::Kind::Object(graph::ObjectValue { fields })),
    }
}

fn list(values: Vec<graph::Value>) -> graph::Value {
    graph::Value {
        kind: Some(graph::value::Kind::List(graph::ListValue { values })),
    }
}

fn tier_name(tier: &str) -> &'static str {
    match tier {
        "T0" => "perimeter",
        "T1" => "reachability",
        "T2" => "path",
        "T3" => "body",
        "T4" => "proof",
        _ => "unknown",
    }
}

fn contract_tier<'a>(kind: &str, fallback: &'a str) -> &'a str {
    match kind {
        "file" | "directory" | "package" | "module" => "T0",
        "declaration" | "definition" | "function" | "method" | "constructor"
        | "class" | "interface" | "type" | "enum" | "record" | "macro" => "T1",
        "parameter" | "variable" | "binding" | "property" | "constant"
        | "value" | "expression-value" | "argument" | "call-value"
        | "return" | "return-value" => "T2",
        "statement" | "expression" | "call" | "operator" | "literal"
        | "allocation" | "read" | "write" | "release" => "T3",
        _ => fallback,
    }
}

fn is_structural_edge(kind: &str) -> bool {
    matches!(
        kind,
        "DECLARES"
            | "DECLARES_MEMBER"
            | "DECLARES_VALUE"
            | "CONTAINS_BODY"
            | "AST_CHILD"
            | "EVIDENCED_BY"
            | "HAS_ARGUMENT"
    )
}

fn write_frontend_bundle(
    output: &Path,
    shard: &Path,
    frontend_id: &str,
    node_count: u64,
    _edge_count: u64,
) -> io::Result<(u64, u64)> {
    let mut tier_files: FxHashMap<&'static str, File> = FxHashMap::default();
    for tier in ["T0", "T1", "T2", "T3", "T4"] {
        let name = tier_name(tier);
        let path = output.join(format!("{}_{}.pb", tier.to_lowercase(), name));
        let mut file = File::create(path)?;
        write_delimited(&mut file, 1, tier.as_bytes())?;
        write_delimited(&mut file, 2, name.as_bytes())?;
        tier_files.insert(tier, file);
    }

    let mut node_tiers: FxHashMap<IdKey, String> = FxHashMap::default();
    let mut node_counts: FxHashMap<String, u64> = FxHashMap::default();
    let mut node_stream = File::open(shard.join("nodes.pb"))?;
    while let Some(payload) = read_frame(&mut node_stream)? {
        let mut record = graph::NodeRecord::decode(payload.as_slice())?;
        let initial_tier = if record.tier.is_empty() {
            "T0".to_owned()
        } else {
            record.tier.clone()
        };
        let tier = contract_tier(&record.kind, &initial_tier).to_owned();
        record.tier = tier.clone();
        add_contract_defaults(&mut record.properties, frontend_id, true);
        node_tiers.insert(id_key(&record.id), tier.clone());
        *node_counts.entry(tier.clone()).or_default() += 1;
        let encoded = record.encode_to_vec();
        let sink = tier_files
            .get_mut(tier.as_str())
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "invalid node tier"))?;
        write_delimited(sink, 3, &encoded)?;
    }

    let mut edge_counts: FxHashMap<String, (u64, u64, u64)> = FxHashMap::default();
    let mut emitted_edges = 0u64;
    let mut edge_stream = File::open(shard.join("edges.pb"))?;
    while let Some(payload) = read_frame(&mut edge_stream)? {
        let mut record = graph::EdgeRecord::decode(payload.as_slice())?;
        let source_tier = node_tiers.get(&id_key(&record.source)).cloned();
        let target_tier = node_tiers.get(&id_key(&record.target)).cloned();
        if source_tier.is_none() || target_tier.is_none() {
            continue;
        }
        let source_tier = source_tier.unwrap();
        let target_tier = target_tier.unwrap();
        let collection = if source_tier == target_tier {
            "edges"
        } else if is_structural_edge(&record.kind) {
            let original_kind = record.kind.clone();
            record.kind = "EXPANDS_TO".to_owned();
            record.properties.push(field("via", text(&original_kind)));
            "expands_to"
        } else {
            record.properties.push(field("target_tier", text(&target_tier)));
            "links"
        };
        record.source_tier = source_tier.clone();
        record.relationship_class = collection.to_owned();
        add_contract_defaults(&mut record.properties, frontend_id, false);
        let encoded = record.encode_to_vec();
        let sink = tier_files
            .get_mut(source_tier.as_str())
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "invalid edge tier"))?;
        let field_number = match collection {
            "edges" => 4,
            "expands_to" => 5,
            "links" => 6,
            _ => unreachable!(),
        };
        write_delimited(sink, field_number, &encoded)?;
        emitted_edges += 1;
        let counters = edge_counts.entry(source_tier).or_default();
        match collection {
            "edges" => counters.0 += 1,
            "expands_to" => counters.1 += 1,
            "links" => counters.2 += 1,
            _ => unreachable!(),
        }
    }
    drop(tier_files);

    let mut tier_values = Vec::new();
    for tier in ["T0", "T1", "T2", "T3", "T4"] {
        let (edges, expands, links) = edge_counts.get(tier).copied().unwrap_or_default();
        tier_values.push(object(vec![
            field("tier", text(tier)),
            field("name", text(tier_name(tier))),
            field("node_count", integer(*node_counts.get(tier).unwrap_or(&0) as i64)),
            field("edge_count", integer(edges as i64)),
            field("expands_to_count", integer(expands as i64)),
            field("cross_tier_link_count", integer(links as i64)),
            field("file", text(&format!("{}_{}.pb", tier.to_lowercase(), tier_name(tier)))),
        ]));
    }
    let manifest = graph::Document {
        format_version: 1,
        fields: Some(graph::ObjectValue {
            fields: vec![
                field("version", integer(2)),
                field("frontend_contract_version", integer(2)),
                field("frontend_id", text(frontend_id)),
                field("generator", text(frontend_id)),
                field("languages", text_list(vec!["c".to_owned()])),
                field("lexical_tokens", graph::Value { kind: Some(graph::value::Kind::Boolean(false)) }),
                field("capabilities", object(vec![
                    field("lexical", text("none")),
                    field("syntax", text("partial")),
                    field("symbols", text("partial")),
                    field("types", text("partial")),
                    field("calls", text("partial")),
                    field("direct_data_flow", text("partial")),
                ])),
                field("node_count", integer(node_count as i64)),
                field("edge_count", integer(emitted_edges as i64)),
                field("tiers", list(tier_values)),
            ],
        }),
    };
    fs::write(output.join("manifest.pb"), manifest.encode_to_vec())?;
    Ok((node_count, emitted_edges))
}

/// The streaming runner consumes the framed shard directly.  It still needs the
/// small frontend manifest, but it does not need the tier bundle: producing that
/// bundle would decode and re-encode every node and edge a second time only for
/// the runner to discard it in `_stream_bundle_to_shard`.
fn write_stream_manifest(
    output: &Path, frontend_id: &str, node_count: u64, edge_count: u64,
) -> io::Result<()> {
    let manifest = graph::Document {
        format_version: 1,
        fields: Some(graph::ObjectValue {
            fields: vec![
                field("version", integer(2)),
                field("frontend_contract_version", integer(2)),
                field("frontend_id", text(frontend_id)),
                field("generator", text(frontend_id)),
                field("languages", text_list(vec!["c".to_owned()])),
                field("lexical_tokens", graph::Value {
                    kind: Some(graph::value::Kind::Boolean(false)),
                }),
                field("capabilities", object(vec![
                    field("lexical", text("none")),
                    field("syntax", text("partial")),
                    field("symbols", text("partial")),
                    field("types", text("partial")),
                    field("calls", text("partial")),
                    field("direct_data_flow", text("partial")),
                ])),
                field("node_count", integer(node_count as i64)),
                field("edge_count", integer(edge_count as i64)),
            ],
        }),
    };
    fs::write(output.join("manifest.pb"), manifest.encode_to_vec())
}

fn parse_unit(
    index: CXIndex,
    unit: &graph::NativeTranslationUnit,
    emitter: &mut Emitter,
) -> Result<(), Box<dyn std::error::Error>> {
    let source_c = CString::new(unit.path.as_bytes())?;
    let clang_args: Vec<CString> = unit
        .arguments
        .iter()
        .map(|argument| CString::new(argument.as_str()))
        .collect::<Result<_, _>>()?;
    let argument_ptrs: Vec<*const c_char> = clang_args.iter().map(|argument| argument.as_ptr()).collect();

    unsafe {
        let mut translation_unit = ptr::null_mut();
        let error = clang_parseTranslationUnit2(
            index,
            source_c.as_ptr(),
            argument_ptrs.as_ptr(),
            argument_ptrs.len() as c_int,
            ptr::null_mut(),
            0,
            // Include dependencies are collected through clang_getInclusions
            // above and macro declarations are recovered from source text. The
            // detailed preprocessor cursor record would retain every directive
            // and expansion in each TU without adding facts to this frontend.
            0,
            &mut translation_unit,
        );
        if error != CXError_Success || translation_unit.is_null() {
            return Err(format!("clang_parseTranslationUnit2 failed for {}: {error}", unit.path).into());
        }
        let root = clang_getTranslationUnitCursor(translation_unit);
        clang_getInclusions(
            translation_unit,
            collect_inclusion,
            emitter as *mut Emitter as *mut c_void,
        );
        // libclang returns the number of visited children here, not a success
        // status; zero is valid for an empty or diagnostic-only translation unit.
        clang_visitChildren(root, visit, emitter as *mut Emitter as *mut c_void);
        clang_disposeTranslationUnit(translation_unit);
    }
    Ok(())
}

fn source_files(root: &Path) -> io::Result<Vec<PathBuf>> {
    let mut pending = vec![root.to_path_buf()];
    let mut files = Vec::new();
    while let Some(directory) = pending.pop() {
        for entry in fs::read_dir(directory)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_dir() {
                pending.push(path);
                continue;
            }
            if matches!(path.extension().and_then(|extension| extension.to_str()),
                        Some("c" | "h" | "cc" | "cpp" | "cxx" | "hpp")) {
                files.push(path);
            }
        }
    }
    files.sort();
    Ok(files)
}

fn is_header(path: &Path) -> bool {
    matches!(path.extension().and_then(|extension| extension.to_str()),
             Some("h" | "hpp"))
}

fn is_translation_unit(path: &Path) -> bool {
    matches!(path.extension().and_then(|extension| extension.to_str()),
             Some("c" | "cc" | "cpp" | "cxx"))
}

fn include_name(line: &str) -> Option<&str> {
    let rest = line.trim_start().strip_prefix('#')?.trim_start();
    let rest = rest.strip_prefix("include")?.trim_start();
    let (open, close) = match rest.as_bytes().first()? {
        b'"' => ('"', '"'),
        b'<' => ('<', '>'),
        _ => return None,
    };
    let body = rest.strip_prefix(open)?;
    let end = body.find(close)?;
    Some(&body[..end])
}

fn canonical_existing(path: PathBuf) -> Option<PathBuf> {
    let canonical = path.canonicalize().ok()?;
    canonical.is_file().then_some(canonical)
}

fn standalone_roots(files: &[PathBuf]) -> io::Result<Vec<PathBuf>> {
    let mut by_relative: FxHashMap<String, PathBuf> = FxHashMap::default();
    let mut by_name: FxHashMap<String, Vec<PathBuf>> = FxHashMap::default();
    let source_dir = files
        .iter()
        .filter_map(|path| path.parent())
        .min()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    for path in files {
        if !is_header(path) {
            continue;
        }
        if let Ok(relative) = path.strip_prefix(&source_dir) {
            by_relative.insert(relative.to_string_lossy().replace('\\', "/"), path.clone());
        }
        if let Some(name) = path.file_name().and_then(|name| name.to_str()) {
            by_name.entry(name.to_owned()).or_default().push(path.clone());
        }
    }

    let mut included = FxHashSet::default();
    let mut pending: Vec<PathBuf> = files.iter().filter(|path| is_translation_unit(path)).cloned().collect();
    let mut visited = FxHashSet::default();
    while let Some(path) = pending.pop() {
        if !visited.insert(path.clone()) {
            continue;
        }
        let text = fs::read_to_string(&path).unwrap_or_default();
        for line in text.lines() {
            let Some(name) = include_name(line) else { continue };
            let relative = name.replace('\\', "/");
            let candidate = path.parent()
                .and_then(|parent| canonical_existing(parent.join(name)))
                .or_else(|| by_relative.get(&relative).cloned())
                .or_else(|| by_name.get(name).and_then(|paths| {
                    (paths.len() == 1).then(|| paths[0].clone())
                }));
            let Some(candidate) = candidate else { continue };
            if included.insert(candidate.clone()) {
                pending.push(candidate);
            }
        }
    }

    let mut roots: Vec<PathBuf> = files.iter()
        .filter(|path| is_translation_unit(path) || (is_header(path) && !included.contains(*path)))
        .cloned()
        .collect();
    roots.sort();
    roots.dedup();
    Ok(roots)
}

fn automatic_include_arguments(files: &[PathBuf]) -> Vec<String> {
    let mut directories = FxHashSet::default();
    for path in files {
        if let Some(parent) = path.parent() {
            directories.insert(parent.to_path_buf());
        }
    }
    let mut directories: Vec<PathBuf> = directories.into_iter().collect();
    directories.sort();
    directories
        .into_iter()
        .flat_map(|directory| ["-I".to_owned(), directory.to_string_lossy().into_owned()])
        .collect()
}

fn selected_files(input: &Path) -> io::Result<(PathBuf, Vec<PathBuf>)> {
    let source_dir = if input.is_dir() {
        input.to_path_buf()
    } else {
        input.parent().unwrap_or_else(|| Path::new(".")).to_path_buf()
    };
    let roots_file = env::var_os("LACHESIS_ROOTS_FILE");
    if let Some(roots_file) = roots_file {
        let payload = fs::read(roots_file)?;
        let roots = graph::FrontendRoots::decode(payload.as_slice())?;
        if roots.format_version == SHARD_FORMAT_VERSION {
            let mut files: Vec<PathBuf> = roots
                .paths
                .into_iter()
                .map(PathBuf::from)
                .filter(|path| {
                    matches!(path.extension().and_then(|extension| extension.to_str()),
                             Some("c" | "h" | "cc" | "cpp" | "cxx" | "hpp"))
                        && path.is_file()
                })
                .map(|path| path.canonicalize().unwrap_or(path))
                .collect();
            files.sort();
            files.dedup();
            return Ok((source_dir, files));
        }
    }
    let files = if input.is_dir() {
        source_files(input)?
    } else {
        vec![input.to_path_buf()]
    };
    Ok((source_dir, files))
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // clang-sys's `runtime` feature keeps libclang out of the process until
    // the frontend is actually used.  Loading it here also makes the binary
    // self-contained from the Python caller's perspective: Python passes
    // paths and compiler arguments, while Rust owns parsing and protobuf I/O.
    clang_sys::load().map_err(|error| format!("load libclang: {error}"))?;
    let arguments: Vec<String> = env::args().collect();
    if arguments.len() < 3 {
        eprintln!("usage: lachesis-clang-frontend SOURCE OUTPUT_DIR [-- clang-args ...]");
        eprintln!("   or: lachesis-clang-frontend --request REQUEST.pb OUTPUT_DIR");
        std::process::exit(2);
    }
    let request = if arguments[1] == "--request" {
        if arguments.len() < 4 {
            return Err("--request requires REQUEST.pb and OUTPUT_DIR".into());
        }
        Some(graph::NativeFrontendRequest::decode(fs::read(&arguments[2])?.as_slice())?)
    } else {
        None
    };
    let output = PathBuf::from(if request.is_some() { &arguments[3] } else { &arguments[2] });
    let shard = output.join("shard-0");
    fs::create_dir_all(&shard)?;

    unsafe {
        let index = clang_createIndex(0, 0);
        if index.is_null() {
            return Err("clang_createIndex failed".into());
        }
        let mut emitter = Emitter {
            nodes: File::create(shard.join("nodes.pb"))?,
            edges: File::create(shard.join("edges.pb"))?,
            node_ids: FxHashSet::default(),
            edge_ids: FxHashSet::default(),
            node_count: 0,
            edge_count: 0,
            file_ids: FxHashMap::default(),
            root_files: FxHashSet::default(),
            slot_bindings: FxHashMap::default(),
            function_ids: FxHashMap::default(),
            function_definitions: FxHashMap::default(),
            function_declarations: FxHashMap::default(),
            function_parameters: FxHashMap::default(),
            usr_ids: FxHashMap::default(),
            path_cache: FxHashMap::default(),
        };
        if let Some(request) = request.as_ref() {
            emitter.root_files.extend(request.translation_units.iter().map(|unit| {
                PathBuf::from(&unit.path)
                    .canonicalize()
                    .unwrap_or_else(|_| PathBuf::from(&unit.path))
                    .to_string_lossy()
                    .into_owned()
            }));
            for unit in &request.translation_units {
                let path = PathBuf::from(&unit.path)
                    .canonicalize()
                    .unwrap_or_else(|_| PathBuf::from(&unit.path));
                let path_text = path.to_string_lossy().into_owned();
                emit_file_node(&mut emitter, &path_text, &request.source_dir)?;
                emit_macros_for_file(&mut emitter, &path_text)?;
            }
        } else {
            let input = PathBuf::from(&arguments[1])
                .canonicalize()
                .unwrap_or_else(|_| PathBuf::from(&arguments[1]));
            let (source_dir, files) = selected_files(&input)?;
            if files.is_empty() {
                clang_disposeIndex(index);
                return Err(format!("no C or header roots found under {}", source_dir.display()).into());
            }
            let source_dir_text = source_dir.to_string_lossy().into_owned();
            for path in &files {
                let path_text = path.to_string_lossy().into_owned();
                emitter.root_files.insert(path_text.clone());
                emit_file_node(&mut emitter, &path_text, &source_dir_text)?;
                emit_macros_for_file(&mut emitter, &path_text)?;
            }
        }
        if let Some(request) = request {
            if request.translation_units.is_empty() {
                clang_disposeIndex(index);
                return Err("native frontend request contains no translation units".into());
            }
            for unit in &request.translation_units {
                parse_unit(index, unit, &mut emitter)?;
            }
        } else {
            let input = PathBuf::from(&arguments[1])
                .canonicalize()
                .unwrap_or_else(|_| PathBuf::from(&arguments[1]));
            let (_source_dir, files) = selected_files(&input)?;
            let parse_files = standalone_roots(&files)?;
            let mut clang_arguments = Vec::new();
            if let Some(separator) = arguments.iter().position(|argument| argument == "--") {
                clang_arguments.extend(arguments[separator + 1..].iter().cloned());
            }
            if clang_arguments.is_empty() {
                // A directory invocation has no compile database at this native
                // boundary. Make project-local includes resolvable without asking
                // Python to inspect or translate any source/configuration data.
                clang_arguments = automatic_include_arguments(&files);
            }
            for source in parse_files {
                let unit = graph::NativeTranslationUnit {
                    path: source.to_string_lossy().into_owned(),
                    arguments: clang_arguments.clone(),
                };
                parse_unit(index, &unit, &mut emitter)?;
            }
        }
        emit_cross_tu_links(&mut emitter)?;
        emitter.nodes.flush()?;
        emitter.edges.flush()?;
        let node_count = emitter.node_count;
        let edge_count = emitter.edge_count;
        clang_disposeIndex(index);
        write_manifests(&shard, "clang-c-native", node_count, edge_count)?;
        if env::var_os("LACHESIS_SHARD_ROOT").is_some() {
            write_stream_manifest(&output, "clang-c", node_count, edge_count)?;
        } else {
            write_frontend_bundle(&output, &shard, "clang-c", node_count, edge_count)?;
        }
        println!("native clang emitted {node_count} nodes and {edge_count} edges to {}", output.display());
    }
    Ok(())
}
