"""One-shot architecture report — the whole reader, rendered for a human to read.

The nav tools each answer one question an agent asks mid-investigation. A person new to a
codebase wants the opposite: a single page that orients them before they ask anything —
what the tree is, what it is built around, what its subsystems are, and where to start
reading. This assembles that page from tools that already exist, so it invents no new
analysis; it is a projection of the graph into Markdown.

The sections, in the order a reader wants them:

* a header — size, languages, the shape of the graph;
* the spine (`hubs`) — the highest-degree functions, the "start here";
* subsystems by file (`architecture_map`) — the directory-grounded component map;
* function clusters (`communities`) — subsystems as the *call graph* draws them,
  independent of the directory layout, with the cross-cutting connectors named;
* suggested next moves — the exact tool calls that read deeper.

It writes `GRAPH_REPORT.md` beside the caller's choosing and returns the text, so a CLI
verb, a test, and a demo can all reach the same rendering.
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lachesis.nav.graphlib import CALLABLE_KINDS
from lachesis.nav.hubs import Hubs
from lachesis.nav.communities import Communities


def _frontends(gl) -> Counter:
    """Which language frontends contributed, by declaration count — a language mix."""
    langs: Counter = Counter()
    for node in gl.index.nodes_of_kind(*CALLABLE_KINDS):
        fid = node["id"]
        # ids are "v2:frontend:<name>:<kind>:<hash>"; the frontend name is the mix signal.
        parts = fid.split(":")
        if len(parts) >= 3 and parts[1] == "frontend":
            langs[parts[2]] += 1
    return langs


_FRONTEND_LABEL = {
    "cpython-ast": "Python", "typescript-compiler-api": "TypeScript/JavaScript",
    "clang-c": "C",
}


def build_report(store, title: str | None = None, hubs_n: int = 15,
                 communities_n: int = 12, members: int = 6) -> str:
    gl = store.gl
    lines: list[str] = []
    w = lines.append

    name = title or "codebase"
    n_nodes = len(gl.nodes)
    functions = list(gl.index.nodes_of_kind(*CALLABLE_KINDS))
    langs = _frontends(gl)
    lang_str = ", ".join(f"{_FRONTEND_LABEL.get(k, k)} ({v})"
                         for k, v in langs.most_common()) or "—"

    w(f"# Architecture report — {name}")
    w("")
    w("_Generated by lachesis from a compiler-precise code property graph. Every function, "
      "call, and cluster below comes from a real parse — no heuristics, no LLM._")
    w("")
    w("## At a glance")
    w("")
    w(f"- **Graph:** {n_nodes:,} nodes")
    w(f"- **Functions & methods:** {len(functions):,}")
    w(f"- **Languages:** {lang_str}")

    # ------------------------------------------------------------------ spine
    hubs = Hubs(gl, resolved_only=True).top(hubs_n)
    w("")
    w("## Start here — the spine")
    w("")
    w("The highest-degree functions over precise direct calls: what the codebase is built "
      "around. Fan-in is how many functions call it; fan-out is how many it calls. "
      "(Indirect name-dispatch is excluded here so the spine reads as real callers, not "
      "attribute-dispatch collisions.)")
    w("")
    if hubs:
        w("| Function | Where | in | out | flags |")
        w("| --- | --- | --: | --: | --- |")
        for r in hubs:
            flags = ", ".join(r["flags"]) if r["flags"] else ""
            w(f"| `{r['name']}` | {r['handle'] or ''} | {r['fan_in']} | "
              f"{r['fan_out']} | {flags} |")
    else:
        w("_(no call edges)_")

    # --------------------------------------------------- subsystems by file
    arch = store  # architecture_map lives on the comprehension analysis
    w("")
    w("## Subsystems — by file")
    w("")
    w("Files grouped into components by call and dependency edges, grounded in the "
      "directory layout. Each row is a subsystem and the functions it is built around.")
    w("")
    try:
        from lachesis.nav.comprehension import Comprehension
        amap = Comprehension(store).architecture_map(max_communities=communities_n)
        comms = amap.get("communities", [])
        if comms:
            for c in comms:
                hubs_here = ", ".join(f"`{h['name']}`" for h in c.get("hubs", [])[:4])
                files_here = c.get("files", [])
                w(f"- **{c['id']}** — {c['file_count']} files"
                  + (f", built around {hubs_here}" if hubs_here else ""))
                if files_here:
                    w(f"  - files: {', '.join(files_here[:members])}"
                      + (" …" if c['file_count'] > len(files_here[:members]) else ""))
        else:
            w("_(no file-level components)_")
    except Exception as error:  # architecture_map is best-effort in the report
        w(f"_(file-level map unavailable: {error})_")

    # ---------------------------------------------- function clusters (calls)
    comm = Communities(gl)
    result = comm.summary(n=communities_n, members=members)
    w("")
    w("## Function clusters — by the call graph")
    w("")
    w(f"Subsystems as the call graph draws them, independent of the directory layout "
      f"(label propagation over precise calls). **Modularity {result['modularity']}** "
      f"over {result['communities']} clusters — higher is a cleaner separation.")
    w("")
    if result["connectors_removed"]:
        conn = ", ".join(f"`{m['name']}` ({m['degree']})" for m in result["connectors"])
        w(f"_Cross-cutting connectors lifted out before clustering: {conn}._")
        w("")
    for p in result["partitions"]:
        members_here = ", ".join(f"`{m['name']}`" for m in p["members"][:4])
        w(f"- **{p['label']}** cluster — {p['size']} functions, "
          f"cohesion {p['cohesion']} — {members_here}")
        if p["files"]:
            w(f"  - spans: {', '.join(p['files'][:members])}")

    # ------------------------------------------------------------ next moves
    w("")
    w("## Read deeper")
    w("")
    w("Every function above is navigable by name or `file:line`. To go further:")
    w("")
    w("- `lachesis mcp` — serve this graph to an agent, then `callers` / `callees` / "
      "`read_body` to traverse, `reaches` to trace a value from source to sink.")
    w("- `lachesis communities` — the function clusters above, full and as JSON.")
    w("- `lachesis scan` — what an attacker could reach: entrypoints into sensitive effects.")
    w("")
    return "\n".join(lines) + "\n"


def _parser():
    import argparse
    p = argparse.ArgumentParser(description="Assemble a Markdown architecture report.")
    p.add_argument("graph", help="path to the graph store")
    p.add_argument("-o", "--out", default="GRAPH_REPORT.md", help="output path")
    p.add_argument("--title", help="title for the report (defaults to the graph name)")
    p.add_argument("--overlay", help="optional overlay graph")
    p.add_argument("--stdout", action="store_true", help="print instead of writing a file")
    return p


def main(argv: list[str]) -> int:
    from lachesis.nav.graph_store import GraphStore
    args = _parser().parse_args(argv)
    store = GraphStore.load(args.graph, overlay_path=args.overlay).ensure_dataflow_tier()
    title = args.title or Path(args.graph).stem
    text = build_report(store, title=title)
    if args.stdout:
        print(text)
    else:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"wrote {args.out} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
